### PR TITLE
Feature/add optional dbt resource type

### PR DESCRIPTION
**Pull request by yingyingqiqi**
Processing https://github.com/datnguye/dbterd/issues/13

### CODE REVIEW

**Review by datnguye — CHANGES_REQUESTED** [review]
Thanks a lot @yingyingqiqi for the great changes 👍 
There are couple of points required some minor changes if you could help to check as further before merging:
- CI was failed due to Code Quality checks
  - Check out [Setting up an environment](https://github.com/datnguye/dbterd/blob/main/CONTRIBUTING.md#setting-up-an-environment) for more info
  - You can also check out [pyproject.toml](https://github.com/datnguye/dbterd/blob/main/pyproject.toml) to check the auto-format command
- New option should be renamed to remove prefix `dbt-`

Thank you!

**Comment by yingyingqiqi** [comment]
Thank you for the suggestion, @datnguye. I will make the changes this weekend.

**Comment by yingyingqiqi** [comment]
@datnguye  Modified, please continue, thanks!

**Review by datnguye — APPROVED** [review]
Perfect thank you @yingyingqiqi!
I will need to add some more testing and might need to add mermaid support before introducing v0.3.0. With this change I'm gonna create first beta v0.3.0b1 so it's available on pypi soon.

Cheers!

**Pull request merged**
